version: '2'

services:
  mysql:
    image: mysql:5.6.36
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mugugno
      - MYSQL_USER=mugugno
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=SuperSecret123

volumes:
  db_data:
